#! /bin/bash

original="$(git rev-parse --abbrev-ref HEAD)"

git_cmd='git checkout $branch'
docker_cmd='docker build -t $branch .'


branch=spark-master
eval $docker_cmd
eval $git_cmd


branch=spark-worker
eval $docker_cmd
eval $git_cmd

branch=$original
eval $git_cmd
